### ISSUE TITLE
Not working on https website

### ISSUE THREAD

**Issue by Nickeysoft** [theme-next/theme-next-pdf#1]
When my website uses the https protocol, the pdf is not displayed, but under the http protocol I can display it without modifying any settings.

**Comment by stevenjoezhang** [comment]
Can you provide an URL or screenshot?

**Comment by Nickeysoft** [comment]
> Can you provide an URL or screenshot?

https://blog.voidata.com/2019/04/01/refresh-your-skill-tree-1/

<blockquote><div><img src="/images/favicon-16x16-next.png?v=7.0.1" height="14"> 码不停提</div><div><strong><a href="https://blog.voidata.com/2019/04/01/refresh-your-skill-tree-1/index.html">刷新你的技能树（一）JavaScript</a></strong></div><div>引言前后端分离开发方式的流行，带动了传统软件行业的变革。以前经常被诟病的“程序员审美”，现在也终于因为前端程序的介入而被彻底的扭转了。作为软件开发行业的老兵，这两年也终于放下了自己以前的一切开发习惯，去适应现阶段程序开发的趋势，感慨之余也发现自己欠缺的真的是太多了，现代化软件开发流程、方式、工具的改变，让我一开始的时候觉得真是一头雾水，完全不知所云，硬生生自己琢磨了个把月，才慢慢摸到一些门槛。前几</div></blockquote>

**Comment by stevenjoezhang** [comment]
@Nickeysoft 
Replace
```
{% pdf http://image.voidata.com/Understanding-ECMAScript-6.pdf %}
```
with
```
{% pdf https://image.voidata.com/Understanding-ECMAScript-6.pdf %}
```

**Comment by Nickeysoft** [comment]
> @Nickeysoft
> Replace
> 
> ```
> {% pdf http://image.voidata.com/Understanding-ECMAScript-6.pdf %}
> ```
> with
> 
> ```
> {% pdf https://image.voidata.com/Understanding-ECMAScript-6.pdf %}
> ```

My second-level domain "imag" is not on this server and I can't open the https protocol. Do I have to specify the location of the pdf document with https?

**Comment by stevenjoezhang** [comment]
@Nickeysoft Yes, otherwise it will be blocked by the bowser without https

**Comment by Nickeysoft** [comment]
> @Nickeysoft Yes, otherwise it will be blocked by the bowser without https

Ok, it's working fine.
