### ISSUE TITLE
Support for iPhone browser?

### ISSUE THREAD

**Issue by Nickeysoft** [theme-next/theme-next-pdf#2]
Another question, is it not supported on the iPhone's Safari or Chrome browser?

**Comment by stevenjoezhang** [comment]
It supports

**Comment by Nickeysoft** [comment]
> It supports

But my website can't be opened in the phone browser
https://blog.voidata.com/2019/04/01/refresh-your-skill-tree-1/

<blockquote><div><img src="/images/favicon-16x16-next.png?v=7.0.1" height="14"> 码不停提</div><div><strong><a href="https://blog.voidata.com/2019/04/01/refresh-your-skill-tree-1/index.html">刷新你的技能树（一）JavaScript</a></strong></div><div>引言前后端分离开发方式的流行，带动了传统软件行业的变革。以前经常被诟病的“程序员审美”，现在也终于因为前端程序的介入而被彻底的扭转了。作为软件开发行业的老兵，这两年也终于放下了自己以前的一切开发习惯，去适应现阶段程序开发的趋势，感慨之余也发现自己欠缺的真的是太多了，现代化软件开发流程、方式、工具的改变，让我一开始的时候觉得真是一头雾水，完全不知所云，硬生生自己琢磨了个把月，才慢慢摸到一些门槛。前几</div></blockquote>

**Comment by stevenjoezhang** [comment]
It was once working fine, but somehow it's broken now...
I'll fix it

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/pull/794
